workflows:
  ios-release:
    name: iOS Release Build
    environment:
      flutter: stable

      groups:
        - ios_credentials

      vars:
        FIREBASE_APP_ID: "1:563950462964:ios:a42d70b510fffff032bba1"
        FIREBASE_PROJECT_ID: "clubnotification-c0a25"
        GOOGLE_APPLICATION_CREDENTIALS_JSON: Encrypted(GOOGLE_APPLICATION_CREDENTIALS_JSON)
        APNS_KEY_ID: Encrypted(APNS_KEY_ID)
        APNS_TEAM_ID: Encrypted(APNS_TEAM_ID)
        APNS_AUTH_KEY_PATH: ios/certs/push.p12
        IOS_PROVISIONING_PROFILE_PATH: ios/certs/ClubApp__iOS__AppStore.mobileprovision
        P12_PASSWORD: Encrypted(P12_PASSWORD)


    cache:
      cache_paths:
        - $HOME/.pub-cache
        - ios/Pods
        - $HOME/Library/Caches/CocoaPods
        - $FLUTTER_ROOT/bin/cache
        - build/

    scripts:
      - name: Install Firebase CLI
        script: |
          if ! command -v firebase &> /dev/null; then
            printf "Installing Firebase CLI...\n"
            curl -sL https://firebase.tools | bash
          else
            printf "Firebase CLI already installed.\n"
          fi

      - name: Install Flutter dependencies
        script: |
          flutter pub get

      - name: Install iOS Pods
        script: |
          cd ios
          pod install --repo-update
          cd ..

      - name: Verify iOS Capabilities
        script: |
          printf "Checking Push Notifications capability in Info.plist...\n"
          if ! plutil -p ios/Runner/Info.plist | grep -q "aps-environment"; then
            printf "⚠️ aps-environment not set in Info.plist\n"
            exit 1
          fi
          printf "✅ aps-environment found\n"

          printf "Checking Background Modes (remote-notification)...\n"
          if ! plutil -p ios/Runner/Info.plist | grep -q "remote-notification"; then
            printf "⚠️ Background Modes not set\n"
            exit 1
          fi
          printf "✅ Background Modes found\n"

          printf "Checking Runner.entitlements for Push Notifications...\n"
          if [ -f ios/Runner/Runner.entitlements ]; then
            if ! plutil -p ios/Runner/Runner.entitlements | grep -q "aps-environment"; then
              printf "⚠️ aps-environment not set in Runner.entitlements\n"
              exit 1
            fi
            printf "✅ Runner.entitlements OK\n"
          else
            printf "⚠️ Runner.entitlements file not found\n"
            exit 1
          fi

      - name: Build IPA
        script: |
          flutter build ipa --release
          IPA_PATH="build/ios/ipa/Runner.ipa"
          if [ ! -f "$IPA_PATH" ]; then
            printf "❌ IPA not found\n"
            exit 1
          fi
          printf "✅ IPA built at $IPA_PATH\n"

      - name: Upload to Firebase App Distribution
        script: |
          printf "Checking GOOGLE_APPLICATION_CREDENTIALS_JSON...\n"
          if [ -z "$GOOGLE_APPLICATION_CREDENTIALS_JSON" ]; then
            printf "❌ GOOGLE_APPLICATION_CREDENTIALS_JSON is not set!\n"
            exit 1
          fi
          printf "✅ GOOGLE_APPLICATION_CREDENTIALS_JSON is set\n"

          # Save service account JSON correctly
          printf "%s" "$GOOGLE_APPLICATION_CREDENTIALS_JSON" > "$CM_BUILD_DIR/service-account.json"
          export GOOGLE_APPLICATION_CREDENTIALS="$CM_BUILD_DIR/service-account.json"

          IPA_PATH="build/ios/ipa/Runner.ipa"
          if [ ! -f "$IPA_PATH" ]; then
            printf "❌ IPA not found\n"
            exit 1
          fi
          printf "✅ IPA found at $IPA_PATH\n"

          printf "Uploading IPA to Firebase App Distribution...\n"
          firebase appdistribution:distribute "$IPA_PATH" \
            --app "$FIREBASE_APP_ID" \
            --project "$FIREBASE_PROJECT_ID" \
            --release-notes "iOS Test Release" \
            --groups "clubIos"

          # Cleanup
          rm "$CM_BUILD_DIR/service-account.json"
