abstract class StatesApp{}

class ProjectInitialStates extends StatesApp{}
class ChangeShowPassState extends StatesApp{}
class ChangeShowLoadingState extends StatesApp{}
class LoginOrganizationState extends StatesApp{}
class GetMembersDataState extends StatesApp{}
class GetNotificationData extends StatesApp{}
class GetManagersDataState extends StatesApp{}
class AddMembersDataState extends StatesApp{}
class AddManagersDataState extends StatesApp{}
class DeleteManagersDataState extends StatesApp{}
class DeleteMemberDataState extends StatesApp{}
class DeleteSubscriptionsTypeDataState extends StatesApp{}
class ChangeDateState extends StatesApp{}
class EditMembersState extends StatesApp{}
class EditNameOrganizationState extends StatesApp{}
class EditEmailOrganizationState extends StatesApp{}
class EditPasswordOrganizationState extends StatesApp{}
class LogOutOrganizationState extends StatesApp{}
class GetSubscriptionsTypeState extends StatesApp{}
class GetSubscriptionsMemberState extends StatesApp{}
class AddSubscriptionsMembersState extends StatesApp{}
class AddSubscriptionsTypeState extends StatesApp{}
class EditSubscriptionState extends StatesApp{}
class StopSuspendMembersState extends StatesApp{}
class AddSuspendMembersState extends StatesApp{}
class GatSuspendMembersDataState extends StatesApp{}
class GatSuspendSubscriptionsDataState extends StatesApp{}
class StopSuspendSubscriptionsState extends StatesApp{}
class AddSuspendSubscriptionsState extends StatesApp{}
class StopCheckEmailState extends StatesApp{}
class StopForgotPasswordState extends StatesApp{}
class GatInfoOrganizationState extends StatesApp{}
class CheckSubscriptionsState extends StatesApp{}
class CheckTokenState extends StatesApp{}
class GetSectionDataState extends StatesApp{}
class AddSectionDataState extends StatesApp{}
class EditSectionTitleState extends StatesApp{}
class EditSectionDescriptionState extends StatesApp{}
class EditSectionResponsibleState extends StatesApp{}

