// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG_HFsUIYXEG7Wgz-pisZGvkh8_7fNExI',
    appId: '1:563950462964:web:da00d2615583b98b32bba1',
    messagingSenderId: '563950462964',
    projectId: 'clubnotification-c0a25',
    authDomain: 'clubnotification-c0a25.firebaseapp.com',
    storageBucket: 'clubnotification-c0a25.firebasestorage.app',
    measurementId: 'G-2DHC2KFPW0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXWcXqRXf0nR7UeNHImT9Z-j6hk0j9khQ',
    appId: '1:563950462964:android:694618a9a5c4bddf32bba1',
    messagingSenderId: '563950462964',
    projectId: 'clubnotification-c0a25',
    storageBucket: 'clubnotification-c0a25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoJRdC33RZqycM1itIJD0rOI3UWQ6aySM',
    appId: '1:563950462964:ios:a42d70b510fffff032bba1',
    messagingSenderId: '563950462964',
    projectId: 'clubnotification-c0a25',
    storageBucket: 'clubnotification-c0a25.firebasestorage.app',
    iosBundleId: 'com.khadamat.clubapporganizationssection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoJRdC33RZqycM1itIJD0rOI3UWQ6aySM',
    appId: '1:563950462964:ios:f206650b9e6619cf32bba1',
    messagingSenderId: '563950462964',
    projectId: 'clubnotification-c0a25',
    storageBucket: 'clubnotification-c0a25.firebasestorage.app',
    iosBundleId: 'com.example.clubAppOrganizationsSection',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDG_HFsUIYXEG7Wgz-pisZGvkh8_7fNExI',
    appId: '1:563950462964:web:a34fcd7f972dc13232bba1',
    messagingSenderId: '563950462964',
    projectId: 'clubnotification-c0a25',
    authDomain: 'clubnotification-c0a25.firebaseapp.com',
    storageBucket: 'clubnotification-c0a25.firebasestorage.app',
    measurementId: 'G-94VXEC6D1V',
  );
}
